### ISSUE TITLE
My fork is updated

### ISSUE THREAD

**Issue by Treygec** [buzzlawless/live-import-for-ynab#5]
Just leaving a comment here for anyone who comes across this that I have updated my fork to be current with Chase's new email format as of today.

**Comment by buzzlawless** [comment]
Hi @Treygec, thanks for forking and keeping the project up to date :) I can't commit to always keeping this repo up to date, so I encourage you to maintain your fork as well. I had some free time recently so I pushed a commit fixing the Chase parsing, successfully tested with a real transaction today. I tried to use your updated Chase parsing lambda, but ran into errors, so I suspect Chase changed the format yet again after your fix.

**Comment by Treygec** [comment]
Hey @buzzlawless, thanks for updating it again! Hope it wasn't too big a hassle, I got it working in my lambda but never got around to updating my repo.

**Comment by buzzlawless** [comment]
No worries at all, it was fun to implement myself anyway :)

**Comment by buzzlawless** [comment]
Didn't mean to close this, reopening so people are aware of Treygec's fork

**Comment by buzzlawless** [comment]
Closing this since a lot of changes have been made to the repo since. Feel free to repoen if I'm negligent again when it comes to reacting to an email format change ;)
